train:
  root: train_logs
  dataset_name: funiture
  dataset_split_name: train
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture

eval:
  root: eval_logs
  dataset_name: furniture
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture 
  dataset_split_name: validation

test:
  root: test_logs
  list: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture/test.txt
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture/test

model:
  inception_resnet_v2:
    train_dir: inception_resnet_v2
    model_name: inception_resnet_v2
    checkpoint_path: ./checkpoints/inception_resnet_v2_2016_08_30.ckpt
    checkpoint_exclude_scopes: InceptionResnetV2/Logits,InceptionResnetV2/AuxLogit

  inception_v3:
    train_dir: inception_v3
    model_name: inception_v3
    checkpoint_path: ./checkpoints/inception_v3.ckpt
    checkpoint_exclude_scopes: InceptionV3/Logits,InceptionV3/AuxLogits 

  inception_v4:
    train_dir: inception_v4
    model_name: inception_v4
    checkpoint_path: ./checkpoints/inception_v4.ckpt
    checkpoint_exclude_scopes: InceptionV4/Logits,InceptionV4/AuxLogits 

  resnet_v2_152:
    train_dir: resnet_v2_152
    model_name: resnet_v2_152
    checkpoint_path: ./checkpoints/resnet_v2_152.ckpt
    checkpoint_exclude_scopes: resnet_v2_152/logits

  nasnet_large:
    train_dir: nasnet_large
    model_name: nasnet_large
    checkpoint_path: ./checkpoints/nasnet-a_large_04_10_2017/model.ckpt
    checkpoint_exclude_scopes: final_layer,aux_11

  pnasnet_large:
    train_dir: pnasnet_large
    model_name: pnasnet_large
    checkpoint_path: ./checkpoints/pnasnet-5_large_2017_12_13/model.ckpt
    checkpoint_exclude_scopes: final_layer,aux_7