train:
  root: train_logs
  dataset_name: funiture
  dataset_split_name: train
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture

eval:
  root: eval_logs
  dataset_name: furniture
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture 
  dataset_split_name: validation

test:
  root: test_logs
  list: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture/test.txt
  dataset_dir: /data1/jayzjwang/code_res/kaggle_fashion/data/iMaterial_Furniture/test

model:
  inception_resnet_v2:
    train_dir: inception_resnet_v2
    model_name: inception_resnet_v2
    checkpoint_path: ./checkpoints/inception_resnet_v2_2016_08_30.ckpt
    checkpoint_exclude_scopes: InceptionResnetV2/Logits,InceptionResnetV2/AuxLogit

  inception_v3:
    train_dir: inception_v3
    model_name: inception_v3
    checkpoint_path: ./checkpoints/inception_v3.ckpt
    checkpoint_exclude_scopes: InceptionV3/Logits,InceptionV3/AuxLogits 